# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         HTML-HTMLDoc
version:      0.10
version_from: lib/HTML/HTMLDoc.pm
installdirs:  site
requires:
    IPC::Open3:                    

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
